### ISSUE TITLE
Server crash; asdfghjkl

### ISSUE THREAD

**Issue by jjfgiowerf** [ZapCloud/Festivities3#6] opened 2014-12-13 19:27 UTC
---- Minecraft Crash Report ----
// Don't do that.

Time: 13.12.14 23:20
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at com.zapcloudstudios.festivities3.Festivities.preInit(Festivities.java:263)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 34 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 916124592 bytes (873 MB) / 1046937600 bytes (998 MB) up to 1046937600 bytes (998 MB)
    JVM Flags: 3 total; -Xincgc -Xms1G -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 17 mods loaded, 17 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    animalbikes{1.7.10} [Animal Bikes](AnimalBikes_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.0} [Backpack](Backpacks-Mod.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.2.1} [BuildCraft](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.2.1} [BC Transport](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.2.1} [BC Silicon](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.2.1} [BC Builders](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.2.1} [BC Energy](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.2.1} [BC Factory](buildcraft-6.2.1.jar) Unloaded->Constructed->Pre-initialized
    customnpcs{1.7.10b} [CustomNpcs](Custom-NPCs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    festivities3{3.1.2.2} [Festivities3](festivities3-3.1.2.2.jar) Unloaded->Constructed->Errored
    IC2{2.2.654-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized
    RedstonePasteMod{1.6.2} [Redstone Paste](Redstone-Paste-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by jjfgiowerf** [comment] 2014-12-15 19:30
Well, i've installed java 7 but it keeps crashing with any mod version...

**Comment by samsartor** [comment] 2015-01-07 03:16
Duplicate of https://github.com/ZapCloud/Festivities3/issues/8

**Closed as completed by samsartor** 2015-01-07 03:16 UTC
