### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kon07102001** [ZapCloud/Festivities3#7] opened 2014-12-14 12:06 UTC
---- Minecraft Crash Report ----
// My bad.

Time: 14.12.14 17:52
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.getConstructor(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:101)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:85)
    at com.zapcloudstudios.festivities3.Festivities.preInit(Festivities.java:255)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 559137800 bytes (533 MB) / 734527488 bytes (700 MB) up to 3791650816 bytes (3616 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1264 Minecraft Forge 10.13.2.1264 28 mods loaded, 28 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1264} [Forge Mod Loader](forge-1.7.10-10.13.2.1264-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1264} [Minecraft Forge](forge-1.7.10-10.13.2.1264-universal.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.73} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed->Pre-initialized
    furnace3d{1.2.0} [Furnace 3D]([1.7.10] 3D Furnace-1.3a.jar) Unloaded->Constructed->Pre-initialized
    ChickenShed{1.1.3} [Chicken Shed]([1.7.2+] ChickenShed %28v1.1.3%29.jar) Unloaded->Constructed->Pre-initialized
    animalbikes{1.7.10} [Animal Bikes](AnimalBikes_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    animalsPlus{1.2} [Animals+](animalsPlus-1.2.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
    ChestTransporter{2.0.0} [Chest Transporter](ChestTransporter-2.0.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    fairylights{0.3} [Fairy Lights](Fairy-Lights-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    festivities3{3.1.0.1} [Festivities3](festivities3-3.1.0.1.jar) Unloaded->Constructed->Errored
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    LotsOfFood{1.7.10} [Lots of Food](Lots of Food-1.7.10 v4.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by samsartor** [comment] 2015-01-07 03:15
Duplicate of https://github.com/ZapCloud/Festivities3/issues/8

**Closed as completed by samsartor** 2015-01-07 03:15 UTC
